
## .streamlit/config.toml (complete)

```toml
[theme]
# Primary accent color for interactive elements
primaryColor = "#3B82F6"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F3F4F6"

# Color used for almost all text
textColor = "#1F2937"

# Font family for all text in the app, except code blocks
font = "sans serif"

[server]
# Max file size for uploads (in MB)
maxUploadSize = 200

# Max message size for WebSocket (in MB)
maxMessageSize = 200

[browser]
gatherUsageStats = false